version: "3"
services:

# node api service
  backend:
    image: employee-backend:latest
    container_name: employee-backend
    depends_on:
      - mongodb
    environment:
      PORT: 5000
      MONGO_URL: "mongodb+srv://eze:hannaiscool@cluster0.kwza1hi.mongodb.net/?retryWrites=true&w=majority"
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 5000:5000
    command: yarn start

#mongodb service
  mongodb:
    image: mongo:latest
    container_name: employee-db
    restart: always
    volumes:
      - mongodb:/data/db

volumes:
  mongodb: {}
   