FROM node:16.10.0-alpine3.13 as build
WORKDIR /backend
ENV PATH /backend/node_modules/.bin:$PATH
COPY ./package.json /backend/
COPY ./yarn.lock /backend/
RUN yarn
COPY . /backend
CMD ["yarn", "start"]

